# Generated by Django 2.2.7 on 2020-01-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Document/'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
